export const el = {
  playerBoard: document.querySelector(".game-board1"),
  opponentBoard: document.querySelector(".game-board2"),
  shipsContainer: document.querySelector(".all-ships-container"),
  shipsAndbuttonsContainer: document.querySelector(".ships-button-container"),
  confirmFleetBtn: document.querySelector(".confirm-fleet"),
  restartBtn: document.querySelector(".restart-game"),
  RandomiseShipsBtn: document.querySelector(".randomise-ships"),
  resetScoresBtn: document.querySelector(".reset-scores"),
  computerThinking: document.querySelector(".computer-thinking"),
  player1ScoreBoard: document.querySelector(".scoreboard-player1"),
  player2ScoreBoard: document.querySelector(".scoreboard-player2"),
  announcement: document.querySelector(".announcements"),
  dialogBox: document.querySelector(".dialog-box"),
  cancelDialogBtn: document.querySelector(".dialog-close"),
  confirmDialogBtn : document.querySelector(".dialog-confirm"),
  nameInput: document.querySelector(".name-input"),
  dialogInner : document.querySelector(".inner-dialog-box"),
};
